### DISCUSSION TITLE
Quick-Start Guide Request

### DISCUSSION THREAD

**Discussion by simon4477** [yu-i-i/overleaf-cep#11] [Q&A] [answered]
Could you please provide a detailed step-by-step guide on how to deploy `overleaf-cep` using `overleaf-toolkit` for newbies? Does `overleaf-cep` works with the latest CE v5.2.1?

I can run overleaf CE 5.2.1 following the official [Quick-Start Guide](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md) using `overleaf-toolkit`, but I have no idea how to use `overleaf-cep` with overleaf toolkit.

I don't need LDAP or SAML authentication, I am interested in Real-time track changes, comments, Autocomplete of reference keys, and any other premium features etc.

@svdvonde mentioned in [_Other Overleaf Extended Edition_](https://github.com/yu-i-i/overleaf-cep/discussions/9) about an alternative community extension that includes almost all premium features for free (Git Sync, Track Changes, etc.). Is the setup process the same for `overleaf-cep` and that _Other Overleaf Extended Edition_?

**Comment by svdvonde** [comment, marked as answer]
Depends on how newbie. I'm assuming you are already able to set up the standard Overleaf Community Edition using Overleaf Toolkit. If yes, here are the modifications you can make to use Overleaf Toolkit to use this repo's Overleaf Extended Community Edition instead. 

## Installation 
1. Clone the current repo in a folder of your choice. My setup starts in my home directory (`~`) and has a folder `overleaf-cep` and `overleaf-toolkit`.
  ```
  ~/overleaf-cep/<this repo>
  ~/overleaf-toolkit/<standard Overleaf Toolkit>
  ```

2. In `~/overleaf-toolkit/config` you can add a new file called `docker-compose.override.yml`. This file is automatically picked up by Overleaf Toolkit. According to the [installation instructions](https://github.com/yu-i-i/overleaf-cep?tab=readme-ov-file#installation) of this repo the contents should be (at least) the following.

```yml
---
services:
    sharelatex:
        image: sharelatex/sharelatex:ext-ce
```
This says that the `sharelatex` docker image should be `sharelatex/sharelatex:ext-ce`, as opposed to the image that Overleaf Toolkit selects by default.

3. Now you need to build the image. Navigate to the `~/overleaf-cep/server-ce` and run `make`. This will build 2 docker images, a heavyweight "base" image which contains TexLive + some common dependencies, and "community" image which contains the Overleaf services.

4. When the build process completes, you can use Overleaf Toolkit to start overleaf as normal: `bin/up -d`. It will use the `sharelatex/sharelatex:ext-ce` image instead of the standard Overleaf image.

Note that I have not discussed other customisations to configure Overleaf itself. Apart from the customisations that were added by this extended edition (e.g., LDAP auth), the configuration is the same as standard Overleaf/Overleaf Toolkit.

## Maintenance

1. Currently this repository is up-to-date with the `main` branch of the Overleaf Community Edition. When this repository is updated, you can update your local repository. E.g., in my case, I `git pull` in `~/overleaf-cep/`.
2. In most cases it is sufficient to build only the docker image for the Overleaf services, which you can do via `make build-community` (as explained [here](https://github.com/yu-i-i/overleaf-cep?tab=readme-ov-file#overleaf-docker-image)). 
3. When the image has finished building, restart the Overleaf services via Overleaf Toolkit as normal, i.e., `bin/up -d`



## In regards to other extended editions like Overleaf Ruhr

I have not done it, but I guess you can deploy the Overleaf Ruhr edition using the same method as I explained. I would not recommend this because they have hardcoded a few customisations for their use-case at a German university. For example, you can check out Overleaf Ruhr's login page (in German) [here](https://tex.fs-its.rub.de/). You will have to remove those customisations or modify them to your use case, and also keep them up-to-date as the Overleaf Community Edition project keeps getting updates.

If I'm not mistaken their code is also based on an older version of Overleaf, I believe v4.0.5.

**Reply by simon4477** [reply]
Perfect, works like a charm.
Thank you @svdvonde, highly appreciated :)

**Reply by yu-i-i** [reply]
I would just like to add that I created the tag v2.5.1-ext-ce, which is the codebase of Overleaf CE 5.2.1 plus "extended" patches. Additionally, I have uploaded a ready-made image to Docker Hub (see README.md)

**Reply by svdvonde** [reply]
Pardon my ignorance, but I'm unaware of what Overleaf version I am running. I'm just up-to-date with the `ext-ce` branch. Is 5.2.1 recommended, or does it require special upgrade instructions?

**Reply by yu-i-i** [reply]
The ext-ce branch is essentially the latest state of the main upstream branch plus patches. The v2.5.1-ext tag (I just dropped the "-ce" suffix) corresponds to the codebase of the 5.2.1 image plus patches. In theory,  the mainstream image code should be more reliable than the current main branch. So, yes, v5.2.1-ext is recommended. There are no special upgrade instructions—simply check out the v2.5.1-ext tag and build the image, or pull the prebuilt image directly from Docker Hub.

**Comment by IamTaoChen** [comment]
Hi, this is a very nice project. I didn't use the toolkit, I deployed Sharelatx manually(docker-compose + variable.env), I had a problem that the sandbox didn't work.(Others are good).

```env
DOCKER_RUNNER=true
SANDBOXED_COMPILES=true
SIBLING_CONTAINERS_ENABLED=true
SANDBOXED_COMPILES_SIBLING_CONTAINERS=true
SANDBOXED_COMPILES_HOST_DIR="${OVERLEAF_DATA_HOST_PATH}/data/compiles"

# TeX Live
TEX_LIVE_DOCKER_IMAGE=registry.gitlab.com/islandoftex/images/texlive:TL2024-2024-10-13-full
ALL_TEX_LIVE_DOCKER_IMAGES=${TEX_LIVE_DOCKER_IMAGE}
ALL_TEX_LIVE_DOCKER_IMAGE_NAMES=TeXLive-2024
TEX_COMPILER_EXTRA_FLAGS=-shell-escape
```

```yaml
networks:
  mongodb:
    name: ${MONGODB_NETWORK_NAME:-mongodb}
    external: true

  redis:
    name: ${REDIS_NETWORK_NAME:-redis}
    external: true

services:
  sharelatex:
    image: overleafcep/sharelatex:5.3.1-ext-v1
    container_name: ${OVERLEAF_CONTAINER_NAME:-sharelatex}
    hostname: ${OVERLEAF_HOSTNAME:-sharelatex}
    restart: always
    networks:
      mongodb:
      redis:
    ports:
      - ${OVERLEAF_PORT}:80
    env_file:
      - .env
      - ${OVERLEAF_BASE_DIR:-.}/sharelatex.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - ${OVERLEAF_BASE_DIR:-.}/data:/var/lib/overleaf
      - ${OVERLEAF_BASE_DIR:-.}/logs:/var/log/overleaf

```

**Reply by IamTaoChen** [reply]
it works after `TEX_LIVE_DOCKER_IMAGE=texlive/texlive:latest-full`

**Reply by ecesarini** [reply]
> Hi, this is a very nice project. I didn't use the toolkit, I deployed Sharelatx manually(docker-compose + variable.env), I had a problem that the sandbox didn't work.(Others are good).
> 
> ```dotenv
> DOCKER_RUNNER=true
> SANDBOXED_COMPILES=true
> SIBLING_CONTAINERS_ENABLED=true
> SANDBOXED_COMPILES_SIBLING_CONTAINERS=true
> SANDBOXED_COMPILES_HOST_DIR="${OVERLEAF_DATA_HOST_PATH}/data/compiles"
> 
> # TeX Live
> TEX_LIVE_DOCKER_IMAGE=registry.gitlab.com/islandoftex/images/texlive:TL2024-2024-10-13-full
> ALL_TEX_LIVE_DOCKER_IMAGES=${TEX_LIVE_DOCKER_IMAGE}
> ALL_TEX_LIVE_DOCKER_IMAGE_NAMES=TeXLive-2024
> TEX_COMPILER_EXTRA_FLAGS=-shell-escape
> ```
> 
> ```yaml
> networks:
>   mongodb:
>     name: ${MONGODB_NETWORK_NAME:-mongodb}
>     external: true
> 
>   redis:
>     name: ${REDIS_NETWORK_NAME:-redis}
>     external: true
> 
> services:
>   sharelatex:
>     image: overleafcep/sharelatex:5.3.1-ext-v1
>     container_name: ${OVERLEAF_CONTAINER_NAME:-sharelatex}
>     hostname: ${OVERLEAF_HOSTNAME:-sharelatex}
>     restart: always
>     networks:
>       mongodb:
>       redis:
>     ports:
>       - ${OVERLEAF_PORT}:80
>     env_file:
>       - .env
>       - ${OVERLEAF_BASE_DIR:-.}/sharelatex.env
>     volumes:
>       - /etc/timezone:/etc/timezone:ro
>       - /etc/localtime:/etc/localtime:ro
>       - /var/run/docker.sock:/var/run/docker.sock:ro 
>       - ${OVERLEAF_BASE_DIR:-.}/data:/var/lib/overleaf
>       - ${OVERLEAF_BASE_DIR:-.}/logs:/var/log/overleaf
> ```

Hi @IamTaoChen ,
can I ask you some details about your manual deployment?
Did you handle this `docker-compose` file and run `docker compose up`?
I'm very interested on this method but I'm facing some problems with **Mongodb** because the conainer remains in unhealthy state.

Thank you very much

**Reply by IamTaoChen** [reply]
> can I ask you some details about your manual deployment?
> Did you handle this `docker-compose` file and run `docker compose up`?

yes. The `Mongodb` need some special config, I can share my config


```yaml
networks:
  mongodb:
    name: mongodb
    external: false

services:
  mongo:
    image: mongo:${MONGO_VERSION:-7}
    container_name: ${MONGO_CONTAINER_HOSTNAME:-mongo}
    hostname: ${MONGO_HOSTNAME:-mongo}
    restart: always
    networks:
      mongodb:
        aliases:
          - ${MONGO_HOSTNAME:-mongo}
    ports:
      - ${MONGO_PORT:-27017}:27017
    env_file:
      - .env
      - ${MONGO_BASE_DIR:-.}/mongo.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MONGO_BASE_DIR:-.}/data:/data/db 
      - ${MONGO_BASE_DIR:-.}/log:/var/log/mongodb 
      - ${MONGO_BASE_DIR:-.}/config:/etc/mongo 
    command: --replSet rs0 --auth --bind_ip_all --keyFile /etc/mongo/keyfile
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
# mongoDB
```

```bash
➜   tree -L 2
.
├── config
│   ├── keyfile
│   ├── mongod.conf
│   └── permission.sh
```

`permission.sh`
```bash
#/bin/bash
#  openssl rand -base64 756 > keyfile
chown 999:999 keyfile
chmod 600 keyfile
```

`mongod.conf`
```conf
replication:
  replSetName: "rs0"
```
### setup
```
docker exec -it mongo bash
mongosh admin --username root --password {PASSWORD}
rs.initiate({ _id: "rs0", members: [ { _id: 0, host: "mongo:27017" } ] })


mongosh --host mongo --port 27017 -u root -p  admin123A --authenticationDatabase admin
use admin
```
