### DISCUSSION TITLE
Support for sandboxed compiles

### DISCUSSION THREAD

**Discussion by svdvonde** [yu-i-i/overleaf-cep#6] [Ideas]
Hi,

This is not a feature request, but a discussion thereof. How difficult would it be to add support for [sandboxed compiles](https://github.com/overleaf/toolkit/blob/master/doc/sandboxed-compiles.md)? In other words, to support `SIBLING_CONTAINERS_ENABLED=true`. The explanation on [how it works](https://github.com/overleaf/toolkit/blob/master/doc/sandboxed-compiles.md) seems straightforward. For example, for every compile there is currently a folder with a unique identifier, e.g. `data/compiles/<66fa58416a3dcf343967ff0a-66f6b51d324520d1fa1cccbb>/`. This folder contains all project files needed for the compile. I am wondering if it would be feasible to spin up a [texlive](https://hub.docker.com/r/texlive/texlive) docker container that has access only to this folder.

Actually, it looks like there is already code present in the compile service to deal with sandboxed compiles. E.g., [here](https://github.com/yu-i-i/overleaf-cep/blob/fce68d8d188fb67f992affb7590d083634b90366/services/clsi/app/js/DockerRunner.js). I am wondering where these code paths are blocked off for the Community Edition...

**Comment by svdvonde** [comment]
Me and a colleague did some digging. 

In the CLSI (compile service) there is the [following test](https://github.com/yu-i-i/overleaf-cep/blob/fce68d8d188fb67f992affb7590d083634b90366/services/clsi/app/js/CommandRunner.js#L12-L16)

```js
if ((Settings.clsi != null ? Settings.clsi.dockerRunner : undefined) === true) {
  commandRunnerPath = './DockerRunner'
} else {
  commandRunnerPath = './LocalCommandRunner'
}
```

In other words, if `Settings.clsi` exists and `Settings.clsi.dockerRunner` is `true`, then it looks like `DockerRunner` is used. As far as I can see these settings come from [here](https://github.com/yu-i-i/overleaf-cep/blob/fce68d8d188fb67f992affb7590d083634b90366/server-ce/config/settings.js#L51-L53):

```js
  clsi: {
    optimiseInDocker: process.env.OPTIMISE_PDF === 'true',
  },
```

No `Settings.clsi.dockerRunner` to be found. I wonder what happens when changing the `clsi` settings to be:
```js
  clsi: {
    optimiseInDocker: process.env.OPTIMISE_PDF === 'true',
    dockerRunner: true
  },
```

There are a few other variables that overleaf sets in the docker-compose file, which they give as an example to use sibling containers  ([here](https://github.com/overleaf/toolkit/blob/7f10105a9be889d29e3f30a7e7733f678f8c1002/lib/docker-compose.sibling-containers.yml)):

```yml
---
services:
  sharelatex:
    volumes:
      - "${DOCKER_SOCKET_PATH}:/var/run/docker.sock"
    environment:
      DOCKER_RUNNER: 'true'
      SANDBOXED_COMPILES: 'true'
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
      SANDBOXED_COMPILES_HOST_DIR: "${OVERLEAF_DATA_PATH}/data/compiles"
      SYNCTEX_BIN_HOST_PATH: "${OVERLEAF_DATA_PATH}/bin/synctex"
```
